# Generated by Django 5.1 on 2025-04-29 04:08

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("large_file_processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transaction_id", models.BigIntegerField(unique=True)),
                ("transaction_type", models.CharField(max_length=50)),
                ("datetime_utc", models.DateTimeField()),
                ("operator_number", models.CharField(blank=True, max_length=50, null=True)),
                ("operator_name", models.CharField(blank=True, max_length=255, null=True)),
                ("till_id", models.IntegerField()),
                ("till_name", models.CharField(max_length=255)),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                    ),
                ),
                ("nett_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nett_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_sales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxable", models.DecimalField(decimal_places=2, max_digits=10)),
                ("non_taxable", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="large_file_processing.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("line_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nett_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("item_discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_condiment", models.BooleanField(default=False)),
                ("nett_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("category_group", models.CharField(max_length=255)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="large_file_processing.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="large_file_processing.venue",
            ),
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
